### ISSUE TITLE
Status: Error isn't removed once synonyms are saved successfully 

### ISSUE THREAD

**Issue by joehoyle** [humanmade/altis-enhanced-search#132] opened 2020-11-30 14:01 UTC
Steps to reproduce:
1. Enter some synonyms,. save
2. Make sure it somehow errors, leadig to ` Status: ERROR ` being shown
3. Fix underlying error
4. update synonyms

This is what shows: ![](https://joehoyle-captured.s3.amazonaws.com/Screen-Shot-2020-11-30-08-54-57.33-RSNmcvnJxrYPntZTHYGsn0kTXCPHaBMTjHtK8s325GzNDg8ts4FS4DAD1LhR8JsYOwPd1SnhUJwTb2WDFXzA5i1pUrFujmzJT6DP.png)

I'd expect the previously stored error to be cleared once there is a successful save. 

Acceptance criteria:

- [ ] Status: Error is cleared once a successful save is made.

**Comment by robindevitt** [comment] 2022-08-02 11:42
@joehoyle  I'm unable to replicate this point:
> 2. Make sure it somehow errors, leading to Status: ERROR being shown

Do you potentially recall any specific steps to trigger the status error to show?

**Comment by robindevitt** [comment] 2022-08-15 06:45
Closing out as can't reproduce from Joe's steps, although I do believe the issue is resolved.

**Closed by robindevitt** 2022-08-15 06:45 UTC
Labels: bug, should have
